---
Name: silverstripe-opauth
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
OpauthAuthenticator:
  enabled_strategies:
    - FacebookStrategy
    - GoogleStrategy
    - TwitterStrategy
  opauth_security_iteration: 500
  opauth_security_timeout: '2 minutes'
  opauth_callback_transport: 'session'