---
Name: silverstripe-opauth
After: 'framework/*','cms/*'
---
# Add some basic opauth settngs
OpauthAuthenticator:
  opauth_settings:
    security_iteration: 500
    security_timeout: '2 minutes'
    callback_transport: 'session'
# Add many identities to a member, this allows a Member to login to the same
# account with many strategies
Member:
  has_many:
    OpauthIdentities: OpauthIdentity
